require 'common_test'
$: << File.expand_path("../../_common", __FILE__)

require 'lib/testcase'

require "minitest/passing_test"

task :default => :test

desc "Run tests"
task :test do
  MinitestTestcase.new.run
end

