require 'common_test'
$: << File.expand_path("../../_common", __FILE__)

require 'lib/testcase'

require "testunit/passing_test"

task :default => :test

desc "Run tests"
task :test do
  TestUnitTestcase.new.run(:testunit?)
end

